Add backup job

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -53,3 +53,24 @@ jobs:
         run: echo "::set-output name=downloadedData::$(node ./.github/workflows/download-cross-workflow-artifact.js)"
       - name: Post results to Log console
         run: echo "The downloaded ramdom number is ${{ steps.collect_data.outputs.downloadedData }}"
+  # Ref: https://github.community/t/run-github-actions-job-only-if-previous-job-has-failed/174786/2
+  # success-job:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Succeed
+  #       run: |
+  #         exit 0
+  failed-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed
+        run: |
+          exit 1
+  backup-job:
+    runs-on: ubuntu-latest
+    needs: [failed-job]
+    if: always() && needs.failed-job.result == 'failure'
+    steps:
+      - name: Run if dependent job failed
+        run: |
+          echo "Backup job running"
