Failed by error

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -110,16 +110,25 @@ jobs:
   #     - name: Succeed
   #       run: |
   #         exit 0
-  failed-job:
+  # failed-job:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Failed
+  #       run: |
+  #         exit 1
+  error-job:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed
-        run: |
-          exit 1
+      - name: Get PR info
+        id: get_pr_info
+        uses: actions/github-script@v4
+        with:
+          script: |
+            throw new Error("Mock error");
   backup-job:
     runs-on: ubuntu-latest
-    needs: [failed-job]
-    if: always() && needs.failed-job.result == 'failure'
+    needs: [error-job]
+    if: always() && needs.error-job.result == 'failure'
     steps:
       - name: Run if dependent job failed
         run: |
