Move to pr.yml

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -103,3 +103,24 @@ jobs:
             const scriptPath = path.resolve('./.github/workflows/dependabot-comments/index.js');
             const commitHash = '${{ github.event.pull_request.head.sha }}';
             await require(scriptPath)(github, context, core, commitHash, "pr");
+  # Ref: https://github.community/t/run-github-actions-job-only-if-previous-job-has-failed/174786/2
+  # success-job:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Succeed
+  #       run: |
+  #         exit 0
+  failed-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed
+        run: |
+          exit 1
+  backup-job:
+    runs-on: ubuntu-latest
+    needs: [failed-job]
+    if: always() && needs.failed-job.result == 'failure'
+    steps:
+      - name: Run if dependent job failed
+        run: |
+          echo "Backup job running"
